import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Providers from "@/components/Providers";
import { SessionProvider } from "next-auth/react";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
  pageProps
}: Readonly<{
  children: React.ReactNode;
  pageProps?: any;
}>) {
  const session = pageProps?.session;
  return (
    <Providers>
      <SessionProvider session={session}>
        <html lang="en">
          <body className={inter.className}>{children}</body>
        </html>
      </SessionProvider>
    </Providers>
  );
}
